### Free with until and date
POST http://localhost:3000/v1/events/new
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODY4MzY3MDIsImRhdGEiOnsiZG5pIjoiMTIzNDU2NzhaIiwiaWQiOjZ9LCJpYXQiOjE2ODU1NDA3MDJ9.Ox2udZ0DeBVPZ9OWawrzojqlHcSV_EU4gI9QFw2d3bzpQ91Jct6S2tg5pXi5Lgs_4jwOLFNO25lYxLgA9Tx6XD4UaF1mXofndy4yIOSoW2Ilc-g9Op8KVCWyPpRTLdGS9KNytUTLll-kzqcEehhQbR2JTZZR0xbn2BiSUMmLhQZ9e2jGWOEvN3AoJPBMo1el75ibnQIKQ4YpKORGuSEaxRR3k_Mpn2IWAzIgCepcHxuYf67x8HdjsV1PASkVrBBMaPE5Amo10c3co3y4lhSH4uymAZjSGjVx4K8v3J0b6dpLIwb7QkSrE4jbcWHneU5eJdS8yEMc1DxtNXCQJ1bZxQ
Content-Type: application/json

{
  "name": "Free Testing event",
  "visible": false,
  "description": "This is a testing event for checking if development is fine.",
  "stock": 100,
  "until": "202305311200",
  "date": "202306240900"
}
### With prices
POST http://localhost:3000/v1/events/new
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODY4MzY3MDIsImRhdGEiOnsiZG5pIjoiMTIzNDU2NzhaIiwiaWQiOjZ9LCJpYXQiOjE2ODU1NDA3MDJ9.Ox2udZ0DeBVPZ9OWawrzojqlHcSV_EU4gI9QFw2d3bzpQ91Jct6S2tg5pXi5Lgs_4jwOLFNO25lYxLgA9Tx6XD4UaF1mXofndy4yIOSoW2Ilc-g9Op8KVCWyPpRTLdGS9KNytUTLll-kzqcEehhQbR2JTZZR0xbn2BiSUMmLhQZ9e2jGWOEvN3AoJPBMo1el75ibnQIKQ4YpKORGuSEaxRR3k_Mpn2IWAzIgCepcHxuYf67x8HdjsV1PASkVrBBMaPE5Amo10c3co3y4lhSH4uymAZjSGjVx4K8v3J0b6dpLIwb7QkSrE4jbcWHneU5eJdS8yEMc1DxtNXCQJ1bZxQ
Content-Type: application/json

{
  "name": "Paying Testing event",
  "visible": false,
  "description": "This is a testing event for checking if development is fine.",
  "stock": 100,
  "prices": [
    {"section": "default", "price": "20.0"},
    {"section": "fester", "price": "0"}
  ],
  "until": "202305311200",
  "date": "202306240900"
}