### Create new table
POST http://localhost:3000/v1/events/110/table
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODcwMDQwMDUsImRhdGEiOnsiZG5pIjoiMTIzNDU2NzhaIiwiaWQiOjZ9LCJpYXQiOjE2ODU3MDgwMDV9.OJgx0BSkyA9PcsfBzS2LIImNXFIk4wvZbI_l1wKk80NUX-dFLNjFPe92V597CIeKi0xCPYOSpv0XCrYRsttitY9kljdGI-3I6ZnJjgL58_OCGVzRgSCrZiqT0mF1q0zD6yWWMSMK6pJa-8f1-hZ5TA3ABra7XOjJYuc4jfASbaFHnums0lKEFGCJ9BXcJDGBx4CzAdQ_uJBkewTzhebNoiW0PQXiHKEG3D9-sEeHtoMctdIM4xICwvXim0OBtYpL2fOnZK9fnZCVitlwoX0MOOKUMkUUuPeCjy3BF26qMsxllu90fkaJcvCER2YskRE0qladCC0CRnHmmLXZMyQq_w
Content-Type: application/json

{
}