### Get user's data
GET http://localhost:3000/v1/account
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.6MTY4NTM3NjUzOX0.bbUfCtiF9wjZucO_vT4kUFy_18L4OJ040O3wKvp7EdaBKtoqIYy_d61Xz8OJMbe3rvX07O7VA22mmvROOU6waBefg74-S0obLWLWbMM9QRsVbZ6Pbbp72Jn3g-Wv33OhPJOe9ggK0A9I0_cecj4aHSb8-V-w5fNJge9KIH9xO506tCZPIN9fdkymVBARjpDDf56dqETC_CaJniZS-Fh3pUKExDm3_c1yuRyBGR5cSrtgXrdWSZHdQFoY8DWJbCpOY7P8PJfx3KWtgT8prUyseXuvsDwvudnYVilwIfAJDPqrUY-dzaKQv5maafH9ItzDG4Bi_W9ZeWrxFlmdSrKXEQ